default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") { ENV["USER"] } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "" } %>
  host: localhost

development:
  <<: *default
  database: llm_chat_development

test:
  <<: *default
  database: llm_chat_test

production:
  <<: *default
  database: llm_chat_production
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
